In [13]:
from pathlib import Path

PROJECT_ROOT = Path.cwd()

RESULTS_DIR = PROJECT_ROOT / "results"
METRICS_DIR = RESULTS_DIR / "metrics"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

METRICS_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

In [4]:
# Load Afrispeech data

import pandas as pd
from datasets import load_from_disk, Audio

ds = load_from_disk("../data/raw/afrispeech_arrow_16k")
print("Available splits:", ds.keys())

Loading dataset from disk:   0%|          | 0/220 [00:00<?, ?it/s]

Loading dataset from disk:   0%|          | 0/24 [00:00<?, ?it/s]

Available splits: dict_keys(['train', 'validation', 'test'])

In [5]:
# Load test data
# Load test data

test_ds = ds["test"]

print(test_ds)
print("Number of test samples:", len(test_ds))
print("Columns:", test_ds.column_names)

Dataset({
    features: ['speaker_id', 'path', 'audio_id', 'audio', 'transcript', 'age_group', 'gender', 'accent', 'domain', 'country', 'duration'],
    num_rows: 6318
})
Number of test samples: 6318
Columns: ['speaker_id', 'path', 'audio_id', 'audio', 'transcript', 'age_group', 'gender', 'accent', 'domain', 'country', 'duration']

In [7]:
# Convert test metadata to DataFrame

test_df = test_ds.remove_columns(["audio"]).to_pandas()

print("Test metadata shape:", test_df.shape)
display(test_df.head())

Test metadata shape: (6318, 10)

,speaker_id,path,audio_id,transcript,age_group,gender,accent,domain,country,duration
0,cdf91cf6e59ee411b985a40a955d4d1f,/home/ridwan/.cache/huggingface/datasets/downl...,27a83595-3d3f-4a6b-b909-7b8f364d736b/7cb8dfb31...,Protection of the host immune mechanism mighti...,26-40,Female,setswana,clinical,BW,9.730000
1,6d53c4d9134a175a75a020155220ca7f,/home/ridwan/.cache/huggingface/datasets/downl...,80581f4f-9e72-48fb-b4c0-22e6972dbff3/95ddccb7b...,Ask the patient about allergies totape and ski...,19-25,Female,setswana,clinical,ZA,4.526984
2,6d53c4d9134a175a75a020155220ca7f,/home/ridwan/.cache/huggingface/datasets/downl...,13f2d282-bda1-4bc3-83b8-7a0d06e5eda0/933137f33...,"The short, mucus-secreting cells between the c...",19-25,Female,setswana,clinical,ZA,8.563991
3,38a2628beaa524416a8daf826e9d10e2,/home/ridwan/.cache/huggingface/datasets/downl...,99f6019b-4505-4c60-a462-79b0eb6e689a/2cb25e2dd...,Aspiration is terminated when aspirated materi...,26-40,Female,setswana,clinical,BW,9.773991
4,a72b35c5433912b19ec47995b4d1f483,/home/ridwan/.cache/huggingface/datasets/downl...,55d0425c-bd13-4a76-a318-4823e6778eac/c69625cba...,The community members called his mother who wa...,26-40,Female,setswana,general,BW,5.066984

In [8]:
# Load clinical test data
# Load clinical test data

clinical_df = test_df[test_df["domain"].str.lower() == "clinical"].copy()

print("Clinical test samples:", len(clinical_df))
display(clinical_df.head())

Clinical test samples: 3606

,speaker_id,path,audio_id,transcript,age_group,gender,accent,domain,country,duration
0,cdf91cf6e59ee411b985a40a955d4d1f,/home/ridwan/.cache/huggingface/datasets/downl...,27a83595-3d3f-4a6b-b909-7b8f364d736b/7cb8dfb31...,Protection of the host immune mechanism mighti...,26-40,Female,setswana,clinical,BW,9.730000
1,6d53c4d9134a175a75a020155220ca7f,/home/ridwan/.cache/huggingface/datasets/downl...,80581f4f-9e72-48fb-b4c0-22e6972dbff3/95ddccb7b...,Ask the patient about allergies totape and ski...,19-25,Female,setswana,clinical,ZA,4.526984
2,6d53c4d9134a175a75a020155220ca7f,/home/ridwan/.cache/huggingface/datasets/downl...,13f2d282-bda1-4bc3-83b8-7a0d06e5eda0/933137f33...,"The short, mucus-secreting cells between the c...",19-25,Female,setswana,clinical,ZA,8.563991
3,38a2628beaa524416a8daf826e9d10e2,/home/ridwan/.cache/huggingface/datasets/downl...,99f6019b-4505-4c60-a462-79b0eb6e689a/2cb25e2dd...,Aspiration is terminated when aspirated materi...,26-40,Female,setswana,clinical,BW,9.773991
10,1e4033e1ce6f7cce51ca05b1908fc14a,/home/ridwan/.cache/huggingface/datasets/downl...,13600ba0-a4d5-46f7-9235-776cd60bfdee/1404f622c...,Identify the appropriate landmarks for the sit...,19-25,Female,setswana,clinical,BW,6.258980

In [9]:
# Load general test data
general_df = test_df[test_df["domain"].str.lower() == "general"].copy()

print("General test samples:", len(general_df))
display(general_df.head())

General test samples: 2712

,speaker_id,path,audio_id,transcript,age_group,gender,accent,domain,country,duration
4,a72b35c5433912b19ec47995b4d1f483,/home/ridwan/.cache/huggingface/datasets/downl...,55d0425c-bd13-4a76-a318-4823e6778eac/c69625cba...,The community members called his mother who wa...,26-40,Female,setswana,general,BW,5.066984
5,a72b35c5433912b19ec47995b4d1f483,/home/ridwan/.cache/huggingface/datasets/downl...,87603be3-0b58-4176-b897-65995e90eb22/1fb8c8219...,Bilateral ear discharge of 3 days duration and...,26-40,Female,setswana,general,BW,16.920998
6,a72b35c5433912b19ec47995b4d1f483,/home/ridwan/.cache/huggingface/datasets/downl...,91e73902-da52-4922-af16-c9dc81b41515/ecbe70d0c...,Tellurium is an unreactive element.,26-40,Female,setswana,general,BW,2.566984
7,a72b35c5433912b19ec47995b4d1f483,/home/ridwan/.cache/huggingface/datasets/downl...,6d2d6ff9-8dc9-48f2-98dc-1a9d47701870/6f610be4e...,Afro-pop star Adekunle Gold has made his mark ...,26-40,Female,setswana,general,BW,10.576984
8,a72b35c5433912b19ec47995b4d1f483,/home/ridwan/.cache/huggingface/datasets/downl...,f2c988d5-f9a5-4974-a95c-9cd2ba9a0dc6/f60cff2d1...,It has unique themes of the power of ones voic...,26-40,Female,setswana,general,BW,9.788980

In [14]:
# View column details

column_summary = pd.DataFrame({
    "column": test_df.columns,
    "dtype": [test_df[col].dtype for col in test_df.columns],
    "missing_count": [test_df[col].isna().sum() for col in test_df.columns],
    "missing_percent": [round(test_df[col].isna().mean() * 100, 2) for col in test_df.columns],
    "unique_values": [test_df[col].nunique(dropna=True) for col in test_df.columns],
})

display(column_summary)

column_summary.to_csv(METRICS_DIR / "metadata_column_summary.csv", index=False)

       column    dtype  missing_count  missing_percent  unique_values
0  speaker_id      str              0              0.0            750
1        path      str              0              0.0           6318
2    audio_id      str              0              0.0           6318
3  transcript      str              0              0.0           6283
4   age_group      str              0              0.0              6
5      gender      str              0              0.0              3
6      accent      str              0              0.0            108
7      domain      str              0              0.0              2
8     country      str              0              0.0             11
9    duration  float32              0              0.0           5127

In [15]:
# Sample counts per accent for clinical domain
# Sample counts by domain

domain_counts = (
    test_df["domain"]
    .value_counts(dropna=False)
    .reset_index()
)

domain_counts.columns = ["domain", "sample_count"]

display(domain_counts)

domain_counts.to_csv(METRICS_DIR / "sample_counts_by_domain.csv", index=False)

     domain  sample_count
0  clinical          3606
1   general          2712

In [16]:
# Sample counts per accent for clinical domain

clinical_accent_counts = (
    clinical_df["accent"]
    .value_counts(dropna=False)
    .reset_index()
)

clinical_accent_counts.columns = ["accent", "clinical_sample_count"]

display(clinical_accent_counts.head(30))

clinical_accent_counts.to_csv(
    METRICS_DIR / "clinical_sample_counts_by_accent.csv",
    index=False
)

         accent  clinical_sample_count
0        yoruba                    269
1       swahili                    225
2          igbo                    193
3         hausa                    144
4       english                    103
5        anaang                     97
6          mada                     90
7          bini                     86
8       ukwuani                     79
9          zulu                     78
10    mwaghavul                     78
11        luhya                     72
12        bajju                     71
13        berom                     62
14        ikulu                     61
15      isizulu                     60
16        eleme                     60
17        brass                     56
18        ekene                     56
19        agatu                     55
20  ijaw(nembe)                     52
21       ekpeye                     52
22       igarra                     50
23        bassa                     49
24       fulani                     48
25        angas                     45
26        idoma                     44
27        ogbia                     42
28         jaba                     40
29          twi                     39

In [17]:
# Check any missing data on transcripts
# Sample counts per accent for general domain

general_accent_counts = (
    general_df["accent"]
    .value_counts(dropna=False)
    .reset_index()
)

general_accent_counts.columns = ["accent", "general_sample_count"]

display(general_accent_counts.head(30))

general_accent_counts.to_csv(
    METRICS_DIR / "general_sample_counts_by_accent.csv",
    index=False
)

             accent  general_sample_count
0            yoruba                   379
1           swahili                   296
2              igbo                   162
3             eggon                   134
4              zulu                    97
5          setswana                    64
6            kanuri                    59
7     yoruba, hausa                    58
8         afrikaans                    54
9           ukwuani                    54
10          okirika                    54
11            hausa                    52
12            alago                    51
13           ikwere                    50
14             ijaw                    44
15            urobo                    43
16          isizulu                    40
17           anaang                    40
18            etche                    39
19         bekwarra                    38
20         itsekiri                    36
21            jukun                    35
22            delta                    33
23           tswana                    32
24  igbo and yoruba                    29
25             epie                    29
26           ekpeye                    28
27             jaba                    25
28           ibibio                    24
29              ika                    24

In [18]:
# Find duplicated transcript texts
duplicate_transcripts = (
    test_df[test_df["transcript"].duplicated(keep=False)]
    .sort_values("transcript")
)

print("Rows with duplicated transcript text:", len(duplicate_transcripts))
print("Number of repeated transcript texts:", duplicate_transcripts["transcript"].nunique())

display(
    duplicate_transcripts[
        ["audio_id", "speaker_id", "domain", "accent", "country", "duration", "transcript"]
    ].head(30)
)

Rows with duplicated transcript text: 69
Number of repeated transcript texts: 34

,audio_id,speaker_id,domain,accent,country,duration,transcript
4290,693b2072-2b72-4f7c-ba9d-fad1973b43e0/d4afab2f8...,638c0814c16527515bb3db1d6e25afa1,general,alago,NG,14.435987,A very common disease was discovered in Ogamin...
4866,99574a9b-937c-4dbe-b904-443d94803c38/d4afab2f8...,33e28feaae9e298e95471515415a233d,general,eggon,NG,14.328979,A very common disease was discovered in Ogamin...
4925,a1ed87fd-f970-45e0-a002-ffb3419eb86b/5a0fb47d7...,c943dbbb5a34d1efc338a1bdffec2efc,general,eggon,NG,2.557000,ALSO READ FROM NIGERIAN TRIBUNE
5092,6f6c1561-0c31-4081-8932-3468352c12ac/5a0fb47d7...,3f7402dad2ccf1d2f93f931d41ddb72c,general,"yoruba, hausa",NG,2.580998,ALSO READ FROM NIGERIAN TRIBUNE
2069,cad0fed7-fc15-438f-b1c8-9d77d2c291bf/b781d4499...,0cf875b6bbb32d20cc5b024fdcb3161d,general,yoruba,NG,4.008000,Angel says why not? Adding that Sammie likes h...
5853,69ea6a25-fec0-47c0-b263-7211ae07e59b/b781d4499...,a61d694177748b99b776b8a88de83123,general,etche,NG,8.939000,Angel says why not? Adding that Sammie likes h...
1663,75a99cac-094a-4262-bfc8-0fbb86e80b8a/fb576364b...,ff242af1121efb0d3620c3894059865a,clinical,yoruba,NG,8.435987,Arthroscopic treatment of cam-type femoroaceta...
2013,47c6f70d-e658-40d3-a134-79d60e10f5cb/fb576364b...,c1c286866c60d25936cf43b0ebe6a65d,clinical,yoruba,NG,9.696000,Arthroscopic treatment of cam-type femoroaceta...
1733,7a8260d4-be98-4c6a-b31f-ac6cf5c86f53/83d4bd3d6...,d45d613adf3a5eabdbb79c3e604610ad,general,yoruba,NG,10.922994,"As an adult, Simon has become a successful sol..."
4679,2a5d668c-08ce-4005-8c63-9ffcf1b91caf/83d4bd3d6...,09bd3e56216608aba141ac199aceb9f4,general,venda and xitsonga,ZA,17.690998,"As an adult, Simon has become a successful sol..."
2978,07018d26-a2d9-49a1-a404-fa195a62d90d/489c6b19c...,d26754e87a5f81ac0b30a787f238d2b5,general,nembe,NG,19.475986,"Bryan, however, warned that the results from a..."
5790,575c0c39-15de-4382-9eae-9cf1e382c5bc/489c6b19c...,9a65a19b865e25e57cc6c56b4f63c381,general,igarra,NG,10.934989,"Bryan, however, warned that the results from a..."
1077,0218adf3-9575-4925-88af-dda54d47d5ca/35786f035...,f6d533e8dea137a94f7750f7a8080361,general,swahili,KE,14.223991,Claim: A national newspaper and multiple onlin...
1130,3d3a3ef7-1846-460a-818c-7db1b41950e7/35786f035...,e1c00fb2bb781c956d9f1cf477711cea,general,swahili,KE,15.050998,Claim: A national newspaper and multiple onlin...
253,e60899ac-afbc-4972-b7ad-f6653d0d38a5/33e8ff41a...,4c5300a620382e0b72cecd400c42e3a0,general,igbo,NG,2.282993,Each level has a particular theme.
4833,e5c61e64-dad8-49c7-bc21-f20f60208ed8/33e8ff41a...,c650864503024b6056b1db45212bd248,general,eggon,NG,2.802993,Each level has a particular theme.
527,cccf1466-f11e-46b7-afb0-6438a7c7afda/cf509c527...,e841f60f42f4ff4da6e024dab5678aa0,general,zulu,ZA,11.852993,He is the middle child of 5 boys and his broth...
3010,eaddc858-b988-429c-a548-dd2c63fae096/cf509c527...,5856f88ae52888c338fe3ac15d673849,general,ibibio,NG,12.463991,He is the middle child of 5 boys and his broth...
45,4e8ac934-1a9a-44e4-80be-0aa4e6df0bc2/bb9f286c3...,5ce789b9038401b6ce6cf8a23816342f,general,setswana,ZA,13.101995,"He said Zimbabwes new government, which came t..."
4773,b57a5e6f-3f45-4e48-adbe-3389aa0b3f4c/bb9f286c3...,f54eaaf8c521f134caba6b0a1ffc53cf,general,afemai,NG,8.814989,"He said Zimbabwes new government, which came t..."
491,ad4e9164-1eb7-49d3-b66b-5ddda6056b3a/dcd16f6a7...,55618f3f467d215072b2aba769998bfc,general,zulu,ZA,6.480998,"He said, Today, Im dressed as a prison inmate ..."
1554,a39b9873-1d46-4b63-b67d-99d6d39cd21e/dcd16f6a7...,7eb3e6a5562018bc0807fe9aed3d753d,general,yoruba,NG,11.278979,"He said, Today, Im dressed as a prison inmate ..."
3508,71a2a3a0-cb85-40b2-8c0a-b9de92eaba02/0ee270da3...,4fd488237ecdaac17742635e80baa34b,general,ika,NG,15.051000,He was apparently well until 2 days ago when h...
4308,79130f07-34a3-4544-b878-ba16b27db927/0ee270da3...,01c5ab3d209856fe8a17e8d1765f6a61,general,okirika,NG,13.385986,He was apparently well until 2 days ago when h...
340,1c3c83e0-b2ec-4ea8-8536-6325953bc40b/0ee270da3...,d7d20fb939639fe6fc1acabc216e905c,general,igbo,NG,10.488979,He was apparently well until 2 days ago when h...
564,e20b117e-f82d-489b-85e1-e7f520217782/0ee270da3...,682c9d06e8131c1a7015b9d1723b1e8a,general,zulu,ZA,9.376985,He was apparently well until 2 days ago when h...
3602,6deeb090-4cbe-4f8e-abbc-96335bb3881e/0ee270da3...,296c783a383596d3ef645e22d878cb66,general,akan,GH,9.326984,He was apparently well until 2 days ago when h...
1218,322b0e26-df4e-4ccc-8edf-5bc41492f658/ef6da97e3...,34195a5670353fd553d53e8a57a44299,general,swahili,UG,13.641000,I discovered that apart from the craft of acti...
3890,69206dd8-2e89-4f82-8c7d-045bbfb12af3/ef6da97e3...,6653712c0e2c617bfa5f8469d69c2163,general,jaba,NG,10.745986,I discovered that apart from the craft of acti...
5114,7ce5f71a-8b5c-4d0f-865f-3a96449186d4/a916d2a43...,3f7402dad2ccf1d2f93f931d41ddb72c,general,"yoruba, hausa",NG,8.507000,"If effective, the system will be immediately d..."

In [19]:
from IPython.display import display, Audio, Markdown

def play_audio_by_index(idx):
    sample = test_ds[int(idx)]
    audio = sample["audio"]

    print("Index:", idx)
    print("Audio ID:", sample["audio_id"])
    print("Speaker ID:", sample["speaker_id"])
    print("Domain:", sample["domain"])
    print("Accent:", sample["accent"])
    print("Country:", sample["country"])
    print("Duration:", sample["duration"])
    print("Transcript:", sample["transcript"])

    display(Audio(audio["array"], rate=audio["sampling_rate"]))

In [20]:
play_audio_by_index(4290)
play_audio_by_index(4866)

Index: 4290
Audio ID: 693b2072-2b72-4f7c-ba9d-fad1973b43e0/d4afab2f8fefac056f5d94b124863ef6
Speaker ID: 638c0814c16527515bb3db1d6e25afa1
Domain: general
Accent: alago
Country: NG
Duration: 14.435986518859863
Transcript: A very common disease was discovered in Ogaminana by Akaolisa and Onu scientists at Offa university from 1998 to 2006.

Index: 4866
Audio ID: 99574a9b-937c-4dbe-b904-443d94803c38/d4afab2f8fefac056f5d94b124863ef6
Speaker ID: 33e28feaae9e298e95471515415a233d
Domain: general
Accent: eggon
Country: NG
Duration: 14.3289794921875
Transcript: A very common disease was discovered in Ogaminana by Akaolisa and Onu scientists at Offa university from 1998 to 2006.

In [25]:
# Minimum and maximum duration by domain

duration_summary = (
    clinical_df
    .groupby("domain")
    .agg(
        samples=("audio_id", "count"),
        min_duration_seconds=("duration", "min"),
        max_duration_seconds=("duration", "max"),
        mean_duration_seconds=("duration", "mean"),
        median_duration_seconds=("duration", "median"),
        total_duration_hours=("duration", lambda x: x.sum() / 3600),
    )
    .reset_index()
)

# Round numeric columns
duration_summary[
    [
        "min_duration_seconds",
        "max_duration_seconds",
        "mean_duration_seconds",
        "median_duration_seconds",
        "total_duration_hours",
    ]
] = duration_summary[
    [
        "min_duration_seconds",
        "max_duration_seconds",
        "mean_duration_seconds",
        "median_duration_seconds",
        "total_duration_hours",
    ]
].round(2)

display(duration_summary)

,domain,samples,min_duration_seconds,max_duration_seconds,mean_duration_seconds,median_duration_seconds,total_duration_hours
0,clinical,3606,1.0,271.179993,10.53,8.0,10.55

In [27]:
MIN_DURATION = 2.0

short_clips = clinical_df[clinical_df["duration"] < MIN_DURATION]

print("Number of clips shorter than 2 seconds:", len(short_clips))

display(
    short_clips[
        ["audio_id", "speaker_id", "domain", "accent", "country", "duration", "transcript"]
    ].head()
)

Number of clips shorter than 2 seconds: 59

,audio_id,speaker_id,domain,accent,country,duration,transcript
278,03437810-6b23-465d-a535-333649b88f94/97a8376f4...,42da56c6e8e9fed480bfbd8e5c0adaac,clinical,igbo,NG,1.447982,"148, 910, 11151216, 1713EQUIPPING DISTRICT LAB..."
312,16b0ad5e-d1ea-4caf-9106-27e7cb54df07/7c1447634...,eb2ee22ad0d81cd485c869b9a8a6bf91,clinical,igbo,NG,1.843991,A: DROWSY AT TIME.
341,830b16c5-f5d2-4e53-90c3-0d36f096d545/8e99f587b...,dbdd51b6ec42a14e807ad432e872b578,clinical,igbo,NG,1.784989,1. Hiatal hernia .
377,462275ca-db78-4406-9ad8-4ab1c54b7f48/dfa95155f...,4218b2dccc637e31df414f95a892bdb4,clinical,igbo,NG,1.782993,The knots should be tied buccally.
492,9832998d-0f94-4380-a7c1-b9ea2da176ef/e145ef6f1...,a2a222977e6b6eb1e8eb7e518607c75f,clinical,zulu,ZA,1.762993,follicle 12.\n

In [26]:
play_audio_by_index(0)

Index: 0
Audio ID: 27a83595-3d3f-4a6b-b909-7b8f364d736b/7cb8dfb3105e8815c510cdbcb22cff29
Speaker ID: cdf91cf6e59ee411b985a40a955d4d1f
Domain: clinical
Accent: setswana
Country: BW
Duration: 9.729999542236328
Transcript: Protection of the host immune mechanism mightincrease the efcacy of other drugs that inhibit viralreplication.